### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by markvr** [pivotalsoftware/session-managers#11]
Hi,

Many thanks for providing this.

Does it support SSL redis connections?

Thanks!
Mark

**Comment by chisunny** [comment]
anyone can respond? I have also tried with SSL port and it doesn't work. Getting connection read timeout.

**Comment by ccheetham** [comment]
Current implementation does not support SSL, however the good news is that the underlying Jedis client does.  For some background, check out https://github.com/xetorthio/jedis/issues/1417.

The issue is that the current implementation does not fully honor the URI in that it ignores the scheme portion of the URI.  E.g., the following URI config in `context.xml` should trigger SSL support (note the scheme):
```xml
    <Store className="com.gopivotal.manager.redis.RedisStore"
       uri="rediss://localhost:6390/0"
     />
```

Parts of the URI are gleaned and, along with some other props, are used to create the pool.  Unfortunately those parts do not presently include the scheme, ie `redis` vs `rediss`.

I was able to get SSL support working without a whole lot of changes.  The change of interest was to `com.gopivotal.manager.redis.RedisStore::startInternal()` and was along the lines of:

```java
    boolean ssl = ... /* does URI start with 'rediss'? */;
    RedisStore.this.jedisPool = new JedisPool(poolConfig, RedisStore.this.host,
        RedisStore.this.port, RedisStore.this.timeout, RedisStore.this.password, 
        RedisStore.this.database, ssl);
```

**Comment by jkonicki** [comment]
Lets leave this ticket open and work on a proper solution for SSL. At least we can provide the parsing of the URI or have the attributes available to enable SSL.

**Comment by ccheetham** [comment]
Created a branch [ssl-support](/pivotalsoftware/session-managers/tree/ssl-support) with an initial implementation of SSL support.

See the main README for how to configure a Tomcat instance.

See the README in the `redis-store/ssl` directory for how to setup a development environment.
