### ISSUE TITLE
Document persistence manager options and the use of com.gopivotal.manager.SessionFlushValve

### ISSUE THREAD

**Issue by gilesw** [pivotalsoftware/session-managers#39]
The Tomcat persistence manager documentation is pretty lacking. Many people are asking for more detail in the comments section.

When using this manager for a shared session store (possibly what it was not originally designed for) many write ups list the time delay between the creating a session and flushing the sessions to the store being a issue with non-sticky sessions. I assume that this valve is some way of mitigating this:-

`<Valve className="com.gopivotal.manager.SessionFlushValve" />`

Here's the best description of the params that I found:-

```
<Context>

...

    <!-- The idle time in seconds before persisting session is
         maxIdleBackup + processExpiresFrequency * engine.backgroundProcessorDelay.
         The backgroundProcessorDelay is around 10 seconds. This configuration should make Tomcat
         to persist sessions after 20 seconds of idling and hold them in memory as long as each
         instance wants -->
    <Manager className="org.apache.catalina.session.PersistentManager"
      saveOnRestart="true"
      minIdleSwap="-1"
      maxIdleSwap="-1"
      maxIdleBackup="20"
      processExpiresFrequency="1">
      <Store className="org.apache.catalina.session.JDBCStore"
        connectionURL="jdbc:mysql://localhost/tomcat_data"
        driverName="com.mysql.jdbc.Driver"
        connectionName="tomcat"
        connectionPassword="tomcat"
        sessionIdCol="session_id"
        sessionValidCol="valid_session"
        sessionMaxInactiveCol="max_inactive"
        sessionLastAccessedCol="last_access"
        sessionTable="tomcat_sessions"
        sessionAppCol="app_name"
        sessionDataCol="session_data"
      />
    </Manager>
...

</Context>


Problems in this solution

If Tomcat dies unexpectedly, the new sessions served by dead instance are lost. Most likely with the configuration above, sessions newer than 30 seconds will disappear. Also new changes that have been done to session data will be lost.
```

http://pedanttinen.blogspot.co.uk/2012/01/tomcat-clustering-and-session.html

**Comment by ccheetham** [comment]
The valve `com.gopivotal.manager.SessionFlushValve` flushes (ie, saves), the HTTP session to the backend store upon a successful HTTP request (ie, one in which no exceptions thrown in pipeline).  The effect being the session is been saved prior to returning the response.

If you were using the backend as your clustering strategy as opposed to Tomcat node clustering, you can use this valve to ensure session state always persisted between requests.

If, however, you are using Tomcat clustering, this valve is probably not needed since Tomcat has replicated the state to another node.

Does this help?

**Comment by gilesw** [comment]
My understanding is this:-

Whichever /persistence/ backend you use if it's mysql postgres or redis wrapped in:

```
<Manager className="org.apache.catalina.session.PersistentManager">
...
</Manager>
```

It should be governed by the defaults of the rules listed in that example above so sessions are not instantly stored.

So when you add your special:

<Valve className="com.gopivotal.manager.SessionFlushValve" />

It overrides this behaviour?

Does the session flush block Tomcat in anyway?

**Comment by ccheetham** [comment]
Yes and yes.

Every HTTP request is accompanied with a call the store's `save(Session)` method.  See https://github.com/pivotalsoftware/session-managers/blob/master/common/src/main/java/com/gopivotal/manager/SessionFlushValve.java#L150-L157.

This particular valve forwards the request to the valve, and the saves the session.  Because it's part of the pipeline, it's work must complete before a response is returned to the client.

Thus, only enable the valve is Tomcat clustering not enabled.  At a high level, the session is either replicated to the store (in the case of using the valve) or to another node (if using clustering).

**Comment by gilesw** [comment]
Hmm now I'm more confused. Do you use this persistence as well as the built in clustering then? What is the preferred configuration? I'm using it specifically so I can avoid the delta based clustering..

Without clustering enabled if you login to a Tomcat node, create a session. Then shutdown redis. Then visit the other node that request should miss that session.

**Comment by ccheetham** [comment]
There are 3 components/features that can be used/enabled:
* clustering
* persistence
* flush valve

The first 2 are orthogonal:
* Enabling clustering replicates sessions across nodes
* Using a persistence manager reconstitutes state across reboots

Enabling the 3rd, the flush valve, allows you to effect clustering using the persistence backend; it implies you are not using Tomcat clustering.

So ...

If you want a standalone instance that saves sessions across reboots, enable persistence.

If you want a cluster that saves sessions across reboots, enable clustering and persistence.

If you want cluster-like behavior without using Tomcat clustering, enable persistence and the valve.

**Comment by gilesw** [comment]
Okay I've tested and that is the case, thanks for the clear explanation. Option 3 in your list is what I'm going for as I should have a Redis that's always available, either managed on ec2 or using Elasticache.

**Comment by gilesw** [comment]
Can you add your comment to the markdown docs?
